name: Scheduled Report Job

on:
  schedule:
    - cron: "30 18 * * *" # Esempio: ogni giorno alle 19:55 italiane (17:55 UTC)
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Wake up Render app
        run: |
          curl -s https://pomodori-app.onrender.com/

      - name: Wait for app to be fully awake
        run: |
          sleep 240  # Attendi 3 minuti

      - name: Call Render Report API
        env:
          TRIGGER_TOKEN: ${{ secrets.REPORT_TRIGGER_TOKEN }}
        run: |
          curl -X POST https://pomodori-app.onrender.com/api/trigger-report -H "Authorization: Bearer $TRIGGER_TOKEN"
